import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    // The original sidebar from docusaurus
    {type: 'autogenerated', dirName: '.'}
  ],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   "index",
  //   {
  //     type: 'category',
  //     label: '快速上手',
  //     items: [
  //       {
  //         type: 'category',
  //         label: '安装 TVM',
  //         link: {
  //             type:'doc', id: 'install-idx'
  //         },
  //         items: [
  //           {type: 'autogenerated', dirName: 'install'}
  //         ]
  //       },
  //       {
  //         type: 'category',
  //         label: '贡献指南',
  //         link: {
  //             type:'doc', id: 'contribute_idx'
  //         },
  //         items: [
  //           {type: 'autogenerated', dirName: 'contribute'}
  //         ]
  //       },
  //     ],
  //     collapsible: false
  //   },
  //   {
  //     type: 'category',
  //     label: '用户手册',
  //     items: [
  //       {
  //         type: 'category',
  //         label: '用户教程',
  //         link: {
  //             type:'doc', id: 'tutorial_idx'
  //         },
  //         items: [
  //           {type: 'autogenerated', dirName: 'tutorial'}
  //         ]
  //       },
  //       {
  //         type: 'category',
  //         label: '常见问题',
  //         link: {
  //             type:'doc', id: 'how_to_idx'
  //         },
  //         items: [
  //           {type: 'autogenerated', dirName: 'how_to'}
  //         ]
  //       }
  //     ],
  //     collapsible: false
  //   },
  //   {
  //     type: 'category',
  //     label: '开发手册',
  //     items: [
  //       {
  //         type: 'category',
  //         label: '开发者教程',
  //         link: {
  //             type:'doc', id: 'dev/index'
  //         },
  //         items: [
  //           {type: 'autogenerated', dirName: 'dev/tutorial'}
  //         ]
  //       },
  //       {
  //         type: 'category',
  //         label: '开发者指南',
  //         link: {
  //             type:'doc', id: 'dev/how_to'
  //         },
  //         items: [
  //           {type: 'autogenerated', dirName: 'dev/how_to'}
  //         ]
  //       }
  //     ],
  //     collapsible: false
  //   },
  //   {
  //     type: 'category',
  //     label: '设计与架构',
  //     items: [
  //       {
  //         type: 'category',
  //         label: '设计与架构',
  //         link: {
  //             type:'doc', id: 'arch/index'
  //         },
  //         items: [
  //           {type: 'autogenerated', dirName: 'arch/arch'}
  //         ]
  //       }
  //     ],
  //     collapsible: false
  //   },
  //   {
  //     type: 'category',
  //     label: '主题指南',
  //     items: [
  //       { type: 'doc', id: 'topic/microtvm/index' },
  //       {
  //         type: 'category',
  //         label: 'VTA：多功能张量加速器',
  //         link: {
  //             type:'doc', id: 'topic/vta_idx'
  //         },
  //         items: [
  //           {type: 'autogenerated', dirName: 'topic/vta'}
  //         ]
  //       }
  //     ],
  //     collapsible: false
  //   }
  // ]
};

export default sidebars;
