/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [
    // The original sidebar from docusaurus
    {type: 'autogenerated', dirName: '.'}
  ],
  */

  // But you can create a sidebar manually
  tutorialSidebar: [
    "index",
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {type: 'doc', id: 'install/index'},
        {type: 'doc', id: 'contribute/index'},
      ],
      collapsible: false
    },
    {
      type: 'category',
      label: 'User Guide',
      items: [
        {type: 'doc', id: 'user_tutorial/index'},
        {type: 'doc', id: 'user_how_to/index'},
      ],
      collapsible: false
    },
    {
      type: 'category',
      label: 'Developer Guide',
      items: [
        {type: 'doc', id: 'dev/tutorial/index'},
        {type: 'doc', id: 'dev/how_to/how_to'},
      ],
      collapsible: false
    },
    {
      type: 'category',
      label: 'Architecture Guide',
      items: [
        {type: 'doc', id: 'arch/index'},
      ],
      collapsible: false
    },
    {
      type: 'category',
      label: 'Topic Guides',
      items: [
        {type: 'doc', id: 'topic/microtvm/index'},
        {type: 'doc', id: 'topic/vta/index'},
      ],
      collapsible: false
    }
  ]
};

module.exports = sidebars;
